sudo: required
services:
    - docker

before_install:
    - docker build -t hasanmiumiun/docker-react -f Dockerfile.dev .

script:
    - docker run hasanmiumiun/docker-react npm run test -- --coverage

